
-- USERDATA Table Create SQL
CREATE TABLE USERDATA
(
    USERNUM     INT             NOT NULL, 
    ID          VARCHAR2(20)    NOT NULL, 
    PASSWORD    VARCHAR2(30)    NOT NULL, 
    NAME        VARCHAR2(20)    NOT NULL, 
    PHONE       VARCHAR2(30)    NOT NULL, 
    EMAIL       VARCHAR2(60)    NOT NULL, 
    BLACK       VARCHAR2(5)     NOT NULL, 
    CONSTRAINT USERDATA_PK PRIMARY KEY (ID)
);

-- 회원번호 시퀸스
CREATE SEQUENCE USERDATA_SEQ --회원번호는 1000부터 시작
START WITH 1000
INCREMENT BY 1;



--DROP SEQUENCE USERDATA_SEQ;


COMMENT ON TABLE USERDATA IS '유저정보';
COMMENT ON COLUMN USERDATA.USERNUM IS '식별번호';
COMMENT ON COLUMN USERDATA.ID IS '아이디';
COMMENT ON COLUMN USERDATA.PASSWORD IS '패스워드';
COMMENT ON COLUMN USERDATA.NAME IS '이름';
COMMENT ON COLUMN USERDATA.PHONE IS '전화번호';
COMMENT ON COLUMN USERDATA.EMAIL IS '이메일';
COMMENT ON COLUMN USERDATA.BLACK IS '블랙리스트여부';


-- USERDATA Table Create SQL
CREATE TABLE ENGINEERDATA
(
    ENGNUM      INT              NOT NULL, 
    ID          VARCHAR2(20)     NOT NULL, 
    PASSWORD    VARCHAR2(30)     NOT NULL, 
    NAME        VARCHAR2(20)     NOT NULL, 
    PHONE       VARCHAR2(30)     NOT NULL, 
    EMAIL       VARCHAR2(60)         NOT NULL, 
    INTRO       VARCHAR2(100)    NOT NULL, 
    AREA        VARCHAR2(30)     NOT NULL, 
    STATE       VARCHAR2(5)      NOT NULL, 
    CONSTRAINT ENGINEERDATA_PK PRIMARY KEY (ID)
);


CREATE SEQUENCE ENGINEERDATA_SEQ
START WITH 1
INCREMENT BY 1;


--DROP SEQUENCE ENGINEERDATA_SEQ;


COMMENT ON TABLE ENGINEERDATA IS '수리기사';
COMMENT ON COLUMN ENGINEERDATA.ENGNUM IS '사원번호';
COMMENT ON COLUMN ENGINEERDATA.ID IS '아이디';
COMMENT ON COLUMN ENGINEERDATA.PASSWORD IS '패스워드';
COMMENT ON COLUMN ENGINEERDATA.NAME IS '이름';
COMMENT ON COLUMN ENGINEERDATA.PHONE IS '전화번호';
COMMENT ON COLUMN ENGINEERDATA.EMAIL IS '이메일';
COMMENT ON COLUMN ENGINEERDATA.INTRO IS '소개메세지';
COMMENT ON COLUMN ENGINEERDATA.AREA IS '근무지역';
COMMENT ON COLUMN ENGINEERDATA.STATE IS '상태';

-- USERDATA Table Create SQL

CREATE TABLE ECOPHONEPRICE
(
    NUM        INT             NOT NULL, 
    FACTORY    VARCHAR2(20)    NOT NULL, 
    MODEL      VARCHAR2(20)    NOT NULL, 
    PRICE      INT             NOT NULL, 
    STATE      VARCHAR2(5)     NOT NULL, 
    CONSTRAINT ECOPHONEPRICE_PK PRIMARY KEY (NUM)
);


CREATE SEQUENCE ECOPHONEPRICE_SEQ
START WITH 1
INCREMENT BY 1;


--DROP SEQUENCE ECOPHONEPRICE_SEQ;


COMMENT ON COLUMN ECOPHONEPRICE.NUM IS '식별번호';
COMMENT ON COLUMN ECOPHONEPRICE.FACTORY IS '제조사';
COMMENT ON COLUMN ECOPHONEPRICE.MODEL IS '기종';
COMMENT ON COLUMN ECOPHONEPRICE.PRICE IS '가격';
COMMENT ON COLUMN ECOPHONEPRICE.STATE IS '상태';

-- USERDATA Table Create SQL
CREATE TABLE FIXSITU
(
    NUM        INT             NOT NULL, 
    CONTENT    VARCHAR2(50)    NOT NULL, 
    STATE      VARCHAR2(5)     NOT NULL, 
    CONSTRAINT FIXSITU_PK PRIMARY KEY (NUM)
);


CREATE SEQUENCE FIXSITU_SEQ
START WITH 1
INCREMENT BY 1;

--DROP SEQUENCE FIXSITU_SEQ;

COMMENT ON TABLE FIXSITU IS '고장상황리스트';
COMMENT ON COLUMN FIXSITU.NUM IS '식별번호';
COMMENT ON COLUMN FIXSITU.CONTENT IS '내용';
COMMENT ON COLUMN FIXSITU.STATE IS '상태';


-- USERDATA Table Create SQL
CREATE TABLE RESLIST
(
    NUM        INT              NOT NULL, 
    TIME       TIMESTAMP        NOT NULL, 
    ADDRESS    VARCHAR2(60)     NULL, 
    USERID     VARCHAR2(20)     NOT NULL, 
    ENGID      VARCHAR2(20)     NOT NULL, 
    FACTORY    VARCHAR2(20)     NOT NULL, 
    MODEL      VARCHAR2(20)     NOT NULL, 
    FAILSIT    VARCHAR2(50)     NOT NULL, 
    FAILMSG    VARCHAR2(100)    NOT NULL, 
    STATE      VARCHAR2(20)     NOT NULL, 
    CONSTRAINT RESLIST_PK PRIMARY KEY (NUM)
);


CREATE SEQUENCE RESLIST_SEQ
START WITH 1
INCREMENT BY 1;

 
--DROP SEQUENCE RESLIST_SEQ;


COMMENT ON TABLE RESLIST IS '예약신청서';
COMMENT ON COLUMN RESLIST.NUM IS '신청서 번호';
COMMENT ON COLUMN RESLIST.TIME IS '신청일시';
COMMENT ON COLUMN RESLIST.ADDRESS IS '출장주소';
COMMENT ON COLUMN RESLIST.USERID IS '신청자 아이디';
COMMENT ON COLUMN RESLIST.ENGID IS '수리기사 아이디';
COMMENT ON COLUMN RESLIST.FACTORY IS '제조사';
COMMENT ON COLUMN RESLIST.MODEL IS '기종';
COMMENT ON COLUMN RESLIST.FAILSIT IS '고장상황';
COMMENT ON COLUMN RESLIST.FAILMSG IS '고장상세상황';
COMMENT ON COLUMN RESLIST.STATE IS '예약상태';

ALTER TABLE RESLIST
    ADD CONSTRAINT FK_RESLIST_USERID_USERDATA_ID FOREIGN KEY (USERID)
        REFERENCES USERDATA (ID);


ALTER TABLE RESLIST
    ADD CONSTRAINT FK_RESLIST_ENGID_ENGINEERDATA_ FOREIGN KEY (ENGID)
        REFERENCES ENGINEERDATA (ID);


ALTER TABLE RESLIST
    ADD CONSTRAINT FK_RESLIST_FAILSIT_FIXSITU_CON FOREIGN KEY (FAILSIT)
        REFERENCES FIXSITU (CONTENT);



-- USERDATA Table Create SQL
CREATE TABLE ADMINDATA
(
    ID          VARCHAR2(20)    NOT NULL, 
    PASSWORD    VARCHAR2(30)    NOT NULL
);


COMMENT ON TABLE ADMINDATA IS '관리자정보';
COMMENT ON COLUMN ADMINDATA.ID IS '아이디';
COMMENT ON COLUMN ADMINDATA.PASSWORD IS '패스워드';



-- USERDATA Table Create SQL
CREATE TABLE ECOPHONE
(
    NUM        INT              NOT NULL, 
    USERID     VARCHAR2(20)     NOT NULL, 
    FACTORY    VARCHAR2(20)     NOT NULL, 
    MODEL      VARCHAR2(20)     NOT NULL, 
    CONTENT    VARCHAR2(100)    NOT NULL, 
    STATE      VARCHAR2(20)     NOT NULL, 
    CONSTRAINT ECOPHONE_PK PRIMARY KEY (NUM)
);


CREATE SEQUENCE ECOPHONE_SEQ
START WITH 1
INCREMENT BY 1;



--DROP SEQUENCE ECOPHONE_SEQ;


COMMENT ON TABLE ECOPHONE IS '에코폰매입 신청서';
COMMENT ON COLUMN ECOPHONE.NUM IS '신청서 번호';
COMMENT ON COLUMN ECOPHONE.USERID IS '신청자ID';
COMMENT ON COLUMN ECOPHONE.FACTORY IS '제조사';
COMMENT ON COLUMN ECOPHONE.MODEL IS '기종';
COMMENT ON COLUMN ECOPHONE.CONTENT IS '제품설명';
COMMENT ON COLUMN ECOPHONE.STATE IS '신청상태';


ALTER TABLE ECOPHONE
    ADD CONSTRAINT FK_ECOPHONE_USERID_USERDATA_ID FOREIGN KEY (USERID)
        REFERENCES USERDATA (ID);


ALTER TABLE ECOPHONE
    ADD CONSTRAINT FK_ECOPHONE_FACTORY_ECOPHONEPR FOREIGN KEY (FACTORY, MODEL)
        REFERENCES ECOPHONEPRICE (FACTORY, MODEL);



-- USERDATA Table Create SQL
CREATE TABLE NOTICE
(
    NUM          INT              NOT NULL, 
    TITLE        VARCHAR2(100)     NOT NULL, 
    CONTENT      VARCHAR2(500)    NOT NULL, 
    VIEWCOUNT    INT              NOT NULL, 
    WRTIME       TIMESTAMP        NOT NULL, 
    CONSTRAINT NOTICE_PK PRIMARY KEY (NUM)
);


CREATE SEQUENCE NOTICE_SEQ
START WITH 1
INCREMENT BY 1;



--DROP SEQUENCE NOTICE_SEQ;


COMMENT ON TABLE NOTICE IS '공지사항';
COMMENT ON COLUMN NOTICE.NUM IS '공지사항번호';
COMMENT ON COLUMN NOTICE.TITLE IS '제목';
COMMENT ON COLUMN NOTICE.CONTENT IS '내용';
COMMENT ON COLUMN NOTICE.VIEWCOUNT IS '조회수';
COMMENT ON COLUMN NOTICE.WRTIME IS '작성시간';



-- USERDATA Table Create SQL
CREATE TABLE FAQ
(
    NUM         INT              NOT NULL, 
    QUESTION    VARCHAR2(300)    NOT NULL, 
    ANSWER      VARCHAR2(300)    NOT NULL, 
    CONSTRAINT FAQ_PK PRIMARY KEY (NUM)
);


CREATE SEQUENCE FAQ_SEQ
START WITH 1
INCREMENT BY 1;


--DROP SEQUENCE FAQ_SEQ;


COMMENT ON TABLE FAQ IS '자주묻는질문';
COMMENT ON COLUMN FAQ.NUM IS '질문번호';
COMMENT ON COLUMN FAQ.QUESTION IS '질문';
COMMENT ON COLUMN FAQ.ANSWER IS '답변';



-- USERDATA Table Create SQL
CREATE TABLE QNA
(
    NUM          INT              NOT NULL, 
    USERID       VARCHAR2(20)     NOT NULL, 
    OPEN         VARCHAR2(5)      NOT NULL, 
    TITLE        VARCHAR2(20)     NOT NULL, 
    CONTENT      VARCHAR2(200)    NOT NULL, 
    VIEWCOUNT    INT              NOT NULL, 
    WRTIME       TIMESTAMP        NOT NULL, 
    ANSWER       VARCHAR2(200)    NULL, 
    ANTIME       TIMESTAMP        NULL, 
    CONSTRAINT QNA_PK PRIMARY KEY (NUM)
);
ALTER TABLE QNA MODIFY title varchar2(50);

CREATE SEQUENCE QNA_SEQ
START WITH 1
INCREMENT BY 1;
                                        

--DROP SEQUENCE QNA_SEQ;


COMMENT ON TABLE QNA IS '상담게시판';
COMMENT ON COLUMN QNA.NUM IS '게시글번호';
COMMENT ON COLUMN QNA.USERID IS '작성유저ID';
COMMENT ON COLUMN QNA.OPEN IS '공개여부';
COMMENT ON COLUMN QNA.TITLE IS '제목';
COMMENT ON COLUMN QNA.CONTENT IS '내용';
COMMENT ON COLUMN QNA.VIEWCOUNT IS '조회수';
COMMENT ON COLUMN QNA.WRTIME IS '작성시간';
COMMENT ON COLUMN QNA.ANSWER IS '답변';
COMMENT ON COLUMN QNA.ANTIME IS '답변작성시간';


ALTER TABLE QNA
    ADD CONSTRAINT FK_QNA_USERID_USERDATA_ID FOREIGN KEY (USERID)
        REFERENCES USERDATA (ID);



-- USERDATA Table Create SQL
CREATE TABLE FIXLIST
(
    NUM        INT             NOT NULL, 
    FACTORY    VARCHAR2(20)    NOT NULL, 
    MODEL      VARCHAR2(20)    NOT NULL, 
    CONSTRAINT FIXLIST_PK PRIMARY KEY (NUM)
);


CREATE SEQUENCE FIXLIST_SEQ
START WITH 1
INCREMENT BY 1;

--DROP SEQUENCE FIXLIST_SEQ;


COMMENT ON TABLE FIXLIST IS '수리가능기종';
COMMENT ON COLUMN FIXLIST.NUM IS '식별번호';
COMMENT ON COLUMN FIXLIST.FACTORY IS '제조사';
COMMENT ON COLUMN FIXLIST.MODEL IS '기종';

-- USERDATA Table Create SQL
CREATE TABLE MONTHSCHEDULE
(
    ENGID      VARCHAR2(20)    NOT NULL, 
    MONTH      INT             NOT NULL, 
    HOLIDAY    DATE            NULL   
);


COMMENT ON TABLE MONTHSCHEDULE IS '엔지니어 월간 스케줄(휴무관리)';
COMMENT ON COLUMN MONTHSCHEDULE.ENGID IS '기사ID';
COMMENT ON COLUMN MONTHSCHEDULE.MONTH IS '해당월';
COMMENT ON COLUMN MONTHSCHEDULE.HOLIDAY IS '휴무일';

ALTER TABLE MONTHSCHEDULE
    ADD CONSTRAINT FK_MONTHSCHEDULE_ENGID_ENGINEE FOREIGN KEY (ENGID)
        REFERENCES ENGINEERDATA (ID);



-- USERDATA Table Create SQL
CREATE TABLE REVIEW
(
    NUM        INT              NOT NULL, 
    FIXNUM     INT              NOT NULL, 
    ENGID      VARCHAR2(20)     NOT NULL, 
    USERID     VARCHAR2(20)     NOT NULL, 
    POINT      INT              NOT NULL, 
    CONTENT    VARCHAR2(200)    NOT NULL, 
    WRTIME     TIMESTAMP        NOT NULL, 
    ANSWER     VARCHAR2(200)    NULL, 
    ANTIME     TIMESTAMP        NULL, 
    CONSTRAINT REVIEW_PK PRIMARY KEY (NUM)
);


CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1;

COMMENT ON TABLE REVIEW IS '후기';
COMMENT ON COLUMN REVIEW.NUM IS '식별번호';
COMMENT ON COLUMN REVIEW.FIXNUM IS '신청서번호';
COMMENT ON COLUMN REVIEW.ENGID IS '수리기사 아이디';
COMMENT ON COLUMN REVIEW.USERID IS '작성유저ID';
COMMENT ON COLUMN REVIEW.POINT IS '평점';
COMMENT ON COLUMN REVIEW.CONTENT IS '내용';
COMMENT ON COLUMN REVIEW.WRTIME IS '작성시간';
COMMENT ON COLUMN REVIEW.ANSWER IS '답변';
COMMENT ON COLUMN REVIEW.ANTIME IS '답변시간';

ALTER TABLE REVIEW
    ADD CONSTRAINT FK_REVIEW_ENGID_ENGINEERDATA_I FOREIGN KEY (ENGID)
        REFERENCES ENGINEERDATA (ID);

ALTER TABLE REVIEW
    ADD CONSTRAINT FK_REVIEW_USERID_USERDATA_ID FOREIGN KEY (USERID)
        REFERENCES USERDATA (ID);

ALTER TABLE REVIEW
    ADD CONSTRAINT FK_REVIEW_FIXNUM_RESLIST_NUM FOREIGN KEY (FIXNUM)
        REFERENCES RESLIST (NUM);


-- USERDATA Table Create SQL
CREATE TABLE DAYSCHEDULE
(
    ENGID    VARCHAR2(20)    NOT NULL, 
    DAY      VARCHAR2(20)    NOT NULL, 
    TIME1    INT             NULL, 
    TIME2    INT             NULL, 
    TIME3    INT             NULL   
);


COMMENT ON TABLE DAYSCHEDULE IS '엔지니어 일간 스케줄(일일 스케줄)';
COMMENT ON COLUMN DAYSCHEDULE.ENGID IS '기사ID';
COMMENT ON COLUMN DAYSCHEDULE.DAY IS '해당일';
COMMENT ON COLUMN DAYSCHEDULE.TIME1 IS 'TIME1';
COMMENT ON COLUMN DAYSCHEDULE.TIME2 IS 'TIME2';
COMMENT ON COLUMN DAYSCHEDULE.TIME3 IS 'TIME3';

ALTER TABLE DAYSCHEDULE
    ADD CONSTRAINT FK_DAYSCHEDULE_ENGID_ENGINEERD FOREIGN KEY (ENGID)
        REFERENCES ENGINEERDATA (ID);



