--일반 insert문
INSERT INTO USERDATA (USERNUM, ID, PASSWORD, NAME, PHONE, EMAIL, BLACK) VALUES (USERDATA_SEQ.nextval,'test01', '1234', 'test1', '01000000000', 'masuri1021@gmail.com', 'false');
INSERT INTO USERDATA (USERNUM, ID, PASSWORD, NAME, PHONE, EMAIL, BLACK) VALUES (USERDATA_SEQ.nextval,'test02', '1234', 'test2', '01000000000', 'masuri1021-2@gmail.com', 'false');
INSERT INTO USERDATA (USERNUM, ID, PASSWORD, NAME, PHONE, EMAIL, BLACK) VALUES (USERDATA_SEQ.nextval,'test03', '1234', 'test3', '01000000000', 'masuri1021-3@gmail.com', 'false');
INSERT INTO USERDATA (USERNUM, ID, PASSWORD, NAME, PHONE, EMAIL, BLACK) VALUES (USERDATA_SEQ.nextval,'test04', '1234', 'test4', '01000000000', 'masuri1021-4@gmail.com', 'false');
INSERT INTO USERDATA (USERNUM, ID, PASSWORD, NAME, PHONE, EMAIL, BLACK) VALUES (USERDATA_SEQ.nextval,'test05', '1234', 'test5', '01000000000', 'masuri1021-5@gmail.com', 'false');

INSERT INTO FAQ (NUM, QUESTION, ANSWER) VALUES (FAQ_SEQ.nextval,'서비스의 안내는 어떻게 볼수 있나요?', '상단에 있는 네비게이션바에서 해당서비스 안내페이지로 이동할수 있습니다.');
INSERT INTO FAQ (NUM, QUESTION, ANSWER) VALUES (FAQ_SEQ.nextval,'서비스의 안내는 어떻게 볼수 있나요?-2', '상단에 있는 네비게이션바에서 해당서비스 안내페이지로 이동할수 있습니다.');
INSERT INTO FAQ (NUM, QUESTION, ANSWER) VALUES (FAQ_SEQ.nextval,'서비스의 안내는 어떻게 볼수 있나요?-3', '상단에 있는 네비게이션바에서 해당서비스 안내페이지로 이동할수 있습니다.');
INSERT INTO FAQ (NUM, QUESTION, ANSWER) VALUES (FAQ_SEQ.nextval,'서비스의 안내는 어떻게 볼수 있나요?-4', '상단에 있는 네비게이션바에서 해당서비스 안내페이지로 이동할수 있습니다.');
INSERT INTO FAQ (NUM, QUESTION, ANSWER) VALUES (FAQ_SEQ.nextval,'서비스의 안내는 어떻게 볼수 있나요?-5', '상단에 있는 네비게이션바에서 해당서비스 안내페이지로 이동할수 있습니다.');
INSERT INTO FAQ (NUM, QUESTION, ANSWER) VALUES (FAQ_SEQ.nextval,'서비스의 안내는 어떻게 볼수 있나요?-7', '상단에 있는 네비게이션바에서 해당서비스 안내페이지로 이동할수 있습니다.');

INSERT INTO NOTICE (NUM, TITLE, CONTENT, VIEWCOUNT, WRTIME) VALUES (NOTICE_SEQ.nextval, '글제목1', '집에있는데  집에 가고 싶다', 0, sysdate);

INSERT INTO ENGINEERDATA (ENGNUM,ID, PASSWORD, NAME, PHONE, EMAIL, INTRO, AREA, STATE) VALUES (ENGINEERDATA_SEQ.nextval,'ID 01', 'PASSWORD 01', 'NAME 01', 'PHONE 01', 'EMAIL 01', 'INTRO 01', 'AREA 01', 'false');
INSERT INTO ENGINEERDATA (ENGNUM,ID, PASSWORD, NAME, PHONE, EMAIL, INTRO, AREA, STATE) VALUES (ENGINEERDATA_SEQ.naxtval,'ID 02', 'PASSWORD 02', 'NAME 02', 'PHONE 02', 'EMAIL 02', 'INTRO 02', 'AREA 02', 'false');
INSERT INTO ENGINEERDATA (ENGNUM,ID, PASSWORD, NAME, PHONE, EMAIL, INTRO, AREA, STATE) VALUES (ENGINEERDATA_SEQ.naxtval,'ID 03', 'PASSWORD 03', 'NAME 03', 'PHONE 03', 'EMAIL 03', 'INTRO 03', 'AREA 03', 'false');
INSERT INTO ENGINEERDATA (ENGNUM,ID, PASSWORD, NAME, PHONE, EMAIL, INTRO, AREA, STATE) VALUES (ENGINEERDATA_SEQ.naxtval,'ID 04', 'PASSWORD 04', 'NAME 04', 'PHONE 04', 'EMAIL 04', 'INTRO 04', 'AREA 04', 'false');
INSERT INTO ENGINEERDATA (ENGNUM,ID, PASSWORD, NAME, PHONE, EMAIL, INTRO, AREA, STATE) VALUES (ENGINEERDATA_SEQ.naxtval,'ID 05', 'PASSWORD 05', 'NAME 05', 'PHONE 05', 'EMAIL 05', 'INTRO 05', 'AREA 05', 'false');
INSERT INTO ENGINEERDATA (ENGNUM,ID, PASSWORD, NAME, PHONE, EMAIL, INTRO, AREA, STATE) VALUES (ENGINEERDATA_SEQ.naxtval,'ID 06', 'PASSWORD 06', 'NAME 06', 'PHONE 06', 'EMAIL 06', 'INTRO 06', 'AREA 06', 'false');
INSERT INTO ENGINEERDATA (ENGNUM,ID, PASSWORD, NAME, PHONE, EMAIL, INTRO, AREA, STATE) VALUES (ENGINEERDATA_SEQ.naxtval,'ID 07', 'PASSWORD 07', 'NAME 07', 'PHONE 07', 'EMAIL 07', 'INTRO 07', 'AREA 07', 'false');
INSERT INTO ENGINEERDATA (ENGNUM,ID, PASSWORD, NAME, PHONE, EMAIL, INTRO, AREA, STATE) VALUES (ENGINEERDATA_SEQ.naxtval,'ID 08', 'PASSWORD 08', 'NAME 08', 'PHONE 08', 'EMAIL 08', 'INTRO 08', 'AREA 08', 'false');
INSERT INTO ENGINEERDATA (ENGNUM,ID, PASSWORD, NAME, PHONE, EMAIL, INTRO, AREA, STATE) VALUES (ENGINEERDATA_SEQ.naxtval,'ID 09', 'PASSWORD 09', 'NAME 09', 'PHONE 09', 'EMAIL 09', 'INTRO 09', 'AREA 09', 'false');
INSERT INTO ENGINEERDATA (ENGNUM,ID, PASSWORD, NAME, PHONE, EMAIL, INTRO, AREA, STATE) VALUES (ENGINEERDATA_SEQ.naxtval,'ID 10', 'PASSWORD 10', 'NAME 10', 'PHONE 10', 'EMAIL 10', 'INTRO 10', 'AREA 10', 'false');

INSERT INTO QNA (num, USERID, OPEN, TITLE, CONTENT, VIEWCOUNT, WRTIME, ANSWER, ANTIME) VALUES (QNA_SEQ.nextval, 'test01', 'TRUE', 'css하기 시러', 'css하기시러 테이블 왜 안맞아 개짜증', 0, sysdate, '침착해', sysdate);
INSERT INTO QNA (num, USERID, OPEN, TITLE, CONTENT, VIEWCOUNT, WRTIME) VALUES (QNA_SEQ.nextval, 'test02', 'TRUE', 'css하기 시러', 'css하기시러 테이블 왜 안맞아 개짜증', 0, sysdate);
INSERT INTO QNA (num, USERID, OPEN, TITLE, CONTENT, VIEWCOUNT, WRTIME, ANSWER, ANTIME) VALUES (QNA_SEQ.nextval, 'test03', 'FALSE', 'css하기 시러', 'css하기시러 테이블 왜 안맞아 개짜증', 0, sysdate, '침착해', sysdate);
INSERT INTO QNA (num, USERID, OPEN, TITLE, CONTENT, VIEWCOUNT, WRTIME) VALUES (QNA_SEQ.nextval, 'test04', 'FALSE', 'css하기 시러', 'css하기시러 테이블 왜 안맞아 개짜증', 0, sysdate);

